### ISSUE TITLE
无法连接PC端sublime text

### ISSUE THREAD

**Issue by tohno-kun** [hyb1996/AutoJs-Sublime-Plugin#1]
手机：一加5（安卓7.1.1），已root，已开启无障碍，跟电脑同一wifi下，使用飞鸽传书可局域网内互发，ping可通
电脑：sublime text 3 version 3143，成功安装该插件，启动服务可见：
`
server listening at :1209
waiting for accepting
`
但手机打开“连接电脑”，输入电脑的ip地址（还试过带上协议名，也试过带上端口号），都无法连接（无connect成功提示，且电脑端sublime text输入后run不成功）。

**Comment by hyb1996** [comment]
应该是防火墙的锅。windows的话，在防火墙的高级设置中增加入站规则，端口为1209。
